export enum SettlementRequestStatus {
	SETTLEMENT_REQUEST_PENDING = 'SETTLEMENT_REQUEST_PENDING', // 이체 요청 전 정산 요청
	SETTLEMENT_REQUEST_APPROVED = 'SETTLEMENT_REQUEST_APPROVED', // 이체 요청 완료
	TRANSFER_RESERVED = 'TRANSFER_RESERVED', // 이체 예약 완료
	TRANSFER_DONE = 'TRANSFER_DONE', // 이체 완료;
}
